### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function get_quota() on null in plugins/account_details/account_details.php:133

### ISSUE THREAD

**Issue by AK666** [texxasrulez/account_details#7]
roundcubemail-1.6.1 

```
PHP Fatal error:  Uncaught Error: Call to a member function get_quota() on null in /srv/www/RoundCube/htdocs/plugins/account_details/account_details.php:133
Stack trace:
#0 /srv/www/RoundCube/htdocs/program/include/rcmail_output_html.php(1484): account_details->infohtml(Array)
#1 [internal function]: rcmail_output_html->xml_command(Array)
#2 /srv/www/RoundCube/htdocs/program/include/rcmail_output_html.php(1322): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:incl...')
#3 /srv/www/RoundCube/htdocs/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml('<roundcube:incl...')
#4 /srv/www/RoundCube/htdocs/program/include/rcmail_output_html.php(654): rcmail_output_html->parse('plugin', false)
#5 /srv/www/RoundCube/htdocs/plugins/account_details/account_details.php(52): rcmail_output_html->send('plugin')
#6 /srv/www/RoundCube/htdocs/program/lib/Roundcube/rcube_plugin_api.php(575): account_details->infostep()
#7 /srv/www/RoundCube/htdocs/program/include/rcmail.php(255): rcube_plugin_api->exec_action in /srv/www/RoundCube/htdocs/plugins/account_details/account_details.php on line 133
```

php -v
```
PHP 7.4.33 (cli) (built: Apr  9 2023 16:49:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

```

php -m
```
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
imap
intl
json
ldap
libxml
mailparse
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```
//  libc-client2007e

/account_details/config.inc.php
`$account_details_config['enable_quota'] = false;`

**Comment by AnViKo-RD** [comment]
LINE 131
```
// $imap = $this->rc->imap;
$imap = $this->rc->storage;

```

**Comment by texxasrulez** [comment]
I have done a total redo of this plugin. I cannot recreate this issue. If persists, reopen issue.
